version: '3.8'

services:
  nginx:
    image: nginx:alpine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
 
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: EmpDB

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

    depends_on:
      - db

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs:/opt/sonarqube/logs
    depends_on:
      - db

volumes:
  grafana-storage:
